---
name: "Artwork"
guid: "7871D3B1-F1B9-4318-9C27-F35998FFBBCC"
version: "1"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Download artwork"
description: >
  Downloads artwork from a repository for various media types.
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.Artwork.dll"
changelog: >
