---
name: "Artwork"
guid: "7871D3B1-F1B9-4318-9C27-F35998FFBBCC"
version: 2
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Download artwork"
description: >
  Downloads artwork from a repository for various media types.

category: "General"
artifacts:
  - "Jellyfin.Plugin.Artwork.dll"
changelog: |-
  - Jellyfin 10.11 support (#27) @crobibero
