---
name: "Artwork"
guid: "7871D3B1-F1B9-4318-9C27-F35998FFBBCC"
version: "1.0.0.0"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Download artwork"
description: >
  Downloads artwork from a repository for various media types.

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Artwork.dll"
changelog: |-
  - Use meta ci (#14) @crobibero
  - update ruleset (#7) @crobibero
  - 10.8 support (#4) @crobibero
  - Fix url image template (#1) @crobibero

  ### Dependency updates ###
  - chore(deps): bump Microsoft.Extensions.Http from 5.0.0 to 6.0.0 (#6) @dependabot
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#2) @dependabot
