name: Sync labels
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/jellyfin/jellyfin-meta-plugins/master/.github/plugin-repo-labels.yaml
          delete-other-labels: true
          token: ${{ secrets.JF_BOT_TOKEN }}
